#!/usr/bin/env bash
if [ -z $HT_USER ]; then
    echo 'Did not find user at $HT_USER variable'
    exit 1
fi

if [ -z $HT_PASS ]; then
    echo 'Did not find password at $HT_PASS variable'
    exit 1
fi

DEST=/etc/ebola2018/proxy/htpasswd
rm -f $DEST
mkdir -p $(dirname $DEST)
htpasswd -bc "$DEST" "$HT_USER" "$HT_PASS"
